articles/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from articles.views import (AddOrRemoveArticleTagView, ArticleTagSearchView, AllArticlesListView, ArticlesByTagListView,
                            ArticlesByAssociationListView, ArticleCommentsListView, CommentCreateView,
                            CommentDetailView, ArticleDetailView, ArticleTagsListView, create_tag_and_add_to_article,
                            AssociationAutocompleteView, SearchableAssociationsListView, CommentUpdateView,
                            CommentDeleteView, DigestListView, DigestDetailView, ReportsTabView, TagTrendReportView,
                            MostUsedTagsReportView, CSVReportView, TagAutocompleteView, AllTagsListView,
                            CreatedByMeTagsListView, TagCoOccurrenceReportView, VisualWordCloudReportView,
                            TextualWordCloudReportView, TagCreateView, ToggleTagFollowershipView,
                            FollowedByMeTagsListView, TextSearchArticleListView, FollowedArticlesListView,
                            CommentedArticlesListView, AssociationProfileView, AssociationProfileCreateView,
                            AssociationProfileUpdateView, MetaTagsListView, CommentedByMeArticlesListView)
from newsprocessor_dashboard import settings

app_name = 'articles'

# ******** ATTENTION! *********
# There are few cases we hard coded urls.
# 1. Wherever Using HTMX path-deps.
#       (currently tag lists and article tags, so careful with 'tags/*' and 'articles/<id>/tags/*'
# 2. Sending request to add tag to article. -> 'articles/<id>/tags/<id>'

urlpatterns = [
    # region Tags
    path('tags/', include([
        # Queries
        path('', AllTagsListView.as_view(), name='tags-all'),
        path('created/', CreatedByMeTagsListView.as_view(), name='tags-created-by-me'),
        path('followed/', FollowedByMeTagsListView.as_view(), name='tags-followed-by-me'),
        path('meta/', MetaTagsListView.as_view(), name='tags-meta'),
        path('search/autocomplete/', TagAutocompleteView.as_view(), name='tags-autocomplete'),

        # Single tag
        # path('<int:pk>/', TagDetailView.as_view(), name='tag-detail'),
        path('create/', TagCreateView.as_view(), name='tag-create'),
        # path('<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
        # path('<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),
        path('<int:pk>/followership/', ToggleTagFollowershipView.as_view(), name='tag-toggle-followership'),
    ])),
    # endregion

    # region Articles
    path('articles/', include([
        # Queries
        path('', AllArticlesListView.as_view(), name='articles-all'),
        path('interested/', FollowedArticlesListView.as_view(), name='articles-by-followed-tags'),
        path('commented/', CommentedArticlesListView.as_view(), name='articles-commented'),
        path('commented-by-me/', CommentedByMeArticlesListView.as_view(), name='articles-commented-by-me'),
        path('by-tag/<int:tag_id>/', ArticlesByTagListView.as_view(), name='articles-by-tag'),
        path('by-association/<int:association_id>/', ArticlesByAssociationListView.as_view(),
             name='articles-by-association'),
        path('search/', TextSearchArticleListView.as_view(), name='articles-text-search'),

        # Single article details
        path('<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),

        path('<int:article_id>/', include([
            # Article tags
            path('tags/', ArticleTagsListView.as_view(), name='article-tags'),
            path('tags/create-and-add/', create_tag_and_add_to_article, name='article-tag-create-and-add'),
            path('tags/<int:tag_id>/', AddOrRemoveArticleTagView.as_view(), name='article-tag-addOrRemove'),
            path('tags/search/', ArticleTagSearchView.as_view(), name='article-tag-search'),

            # Article comment
            path('comments/', ArticleCommentsListView.as_view(), name='article-comments'),
            path('user_comment/', CommentDetailView.as_view(), name='article-usercomment-details'),
            path('comment/create/', CommentCreateView.as_view(), name='article-comment-create'),
            path('user_comment/update/', CommentUpdateView.as_view(), name='article-usercomment-update'),
            path('user_comment/delete/', CommentDeleteView.as_view(), name='article-usercomment-delete'),
        ]))
    ])),
    # endregion

    path('reports/', include([
        path('', ReportsTabView.as_view(), name='tabs-reports'),
        path('tag-trend/', TagTrendReportView.as_view(), name='reports-tag-trend'),
        path('most-used-tags/', MostUsedTagsReportView.as_view(), name='reports-most-used-tags'),
        path('tag-co-occurrence/', TagCoOccurrenceReportView.as_view(), name='reports-tag-co-occurrence'),
        path('visual-wordcloud/', VisualWordCloudReportView.as_view(), name='reports-visual-wordcloud'),
        path('textual-wordcloud/', TextualWordCloudReportView.as_view(), name='reports-textual-wordcloud'),
        path('csv/', CSVReportView.as_view(), name='reports-csv'),
    ])),

    path('digests/', include([
        path('', DigestListView.as_view(), name='digests-list'),
        path('<int:pk>/', DigestDetailView.as_view(), name='digest-detail')
    ])),

    path('assocs/', include([
        path('<slug:association_type>/', SearchableAssociationsListView.as_view(), name='association-list'),
        path('<slug:association_type>/search/', AssociationAutocompleteView.as_view(), name='assoc-autocomplete'),
        path('<int:pk>/profile/', AssociationProfileView.as_view(), name='association-profile'),
        path('<int:pk>/profile/create/', AssociationProfileCreateView.as_view(),
             name='association-profile-create'),
        path('<int:pk>/profile/update/', AssociationProfileUpdateView.as_view(),
             name='association-profile-update'),
    ])),
]

# https://testdriven.io/blog/django-static-files/
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsprocessor_dashboard/urls.py
from django.contrib.auth import views as auth_views

from articles.forms import LoginForm, CustomPasswordChangeForm
from articles.views import HomeView, CustomPasswordChangeView

"""newsprocessor_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.urls import path, include, reverse_lazy

admin.site.site_title = _("News website")
admin.site.site_header = _("News website admin panel")

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include([
        path('login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            authentication_form=LoginForm,
        ), name="login"),
        path('logout/', auth_views.LogoutView.as_view(), name="logout"),
        path('password_change/', CustomPasswordChangeView.as_view(
            success_url=reverse_lazy("home"),
            form_class=CustomPasswordChangeForm,
        ), name="password_change"),
    ])),

    path('', include('articles.urls')),
]

articles/models.py
import datetime

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinLengthValidator
from django.db import models
# TODO: Digest, Filter
from django.db.models.functions import Lower, Now
from django.urls import reverse
from django.utils.translation import pgettext_lazy, gettext_lazy as _
from django_countries.fields import CountryField

from articles.apps import ArticlesConfig
from articles.validators import *


# TODO: test validations using self.assertFieldOutput
class Tag(models.Model):
    # CITextField to case-insensitive fields. Only Postgres
    title = models.CharField(_("Title"), max_length=50, unique=True,
                             validators=[non_empty_english_string, MinLengthValidator(2)])
    creator = models.ForeignKey(User, null=True, blank=True,
                                verbose_name=pgettext_lazy("Tag creator", "Creator"),
                                on_delete=models.SET_NULL,
                                related_name='created_tags')
    followers = models.ManyToManyField(User, blank=True,
                                       verbose_name=pgettext_lazy("Tag followers", "Followers"),
                                       related_name="following_tags", )
    is_meta = models.BooleanField(_("Is meta"), default=False,
                                  help_text=_("Meta tags are not applied to articles automatically"))

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
        ordering = ['title']
        constraints = [
            models.UniqueConstraint(
                Lower('title'),
                name='unique case insensitive title'
            ),
        ]

    def get_absolute_url(self):
        return reverse('articles:tag-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


# class AlternativeTitle(models.Model):
#     title = models.CharField(_("Title"), max_length=24, unique=True,
#                              validators=[non_empty_english_string, MinLengthValidator(2)])
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='alternative_names')
#
#     class Meta:
#         verbose_name = _("Alternative title")
#         verbose_name_plural = _("Alternative titles")
#         ordering = ['tag__title', 'title']
#         constraints = [
#             models.UniqueConstraint(
#                 Lower('title'),
#                 name='unique case insensitive title'
#             ),
#         ]


class ArticleTag(models.Model):
    # TODO: user. settings.AUTH_USER_MODEL --> django.contrib.auth.get_user_model()
    added_by = models.ForeignKey(User, null=True, blank=True,
                                 on_delete=models.SET_NULL,
                                 related_name='applied_tags')

    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)  # , related_name='used_cases')
    article = models.ForeignKey('Article', on_delete=models.CASCADE)  # , related_name='tags')

    # auto_applied = models.BooleanField(_("Auto applied"), default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['tag', 'article'], name='unique_tag_per_article'),
        ]

    # noinspection PyUnresolvedReferences
    def __str__(self):
        return f"{self.tag.title} on {self.article.title[:25]}"


class JournalManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Journal)


class InstitutionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Institution)


class FunderManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Funder)


class Association(models.Model):
    class AssociationType(models.IntegerChoices):
        Journal = 0, _('Journal')
        Institution = 1, _('Institution')
        Funder = 2, _('Funder')

    name = models.CharField(_("Name"), max_length=255, validators=[validate_non_empty_text])
    type = models.IntegerField(_("Type"), choices=AssociationType.choices)
    objects = models.Manager()  # First Manager becomes _default_manager by Django
    journals = JournalManager()
    institutions = InstitutionManager()
    funders = FunderManager()

    def type_object(self):
        return Association.AssociationType(self.type)

    def articles(self) -> models.Manager:
        if self.type == Association.AssociationType.Journal:
            return self.published_articles
        if self.type == Association.AssociationType.Institution:
            return self.researched_articles
        return self.funded_articles

    def get_absolute_url(self):
        return reverse('articles:association-profile', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _("Association")
        verbose_name_plural = _("Associations")
        constraints = [
            models.UniqueConstraint(fields=['name', 'type'], name='unique_name_per_type'),
        ]
        ordering = ['name']

    def __str__(self):
        return self.name[:50]


class AssociationProfile(models.Model):
    association = models.OneToOneField(Association, on_delete=models.CASCADE, primary_key=True, related_name='profile')
    custom_name = models.CharField(_('Persian name'), max_length=255)
    icon = models.ImageField(_('Icon'), upload_to=f'{ArticlesConfig.name}/associations/', null=True, blank=True)
    description = models.TextField(_('Description'), null=True, blank=True)
    country = CountryField(_('Country'), null=True, blank=True, blank_label=_('-- Select country --'))

    # country = models.CharField(_('Country'), choices=, null=True, blank=True)

    def __str__(self):
        return self.custom_name[:50]

    def get_absolute_url(self):
        return self.association.get_absolute_url()

    class Meta:
        verbose_name = _("Association Profile")
        verbose_name_plural = _("Association Profiles")


# TODO: test validations using self.assertFieldOutput
class Article(models.Model):
    default_pagination = 8

    url = models.URLField(_("URL"), unique=True)
    title = models.CharField(_("Title"), max_length=255, unique=True,  # avoiding duplicate or very similar articles
                             validators=[validate_non_empty_text])
    subtitle = models.TextField(pgettext_lazy("News subtitle", "Subtitle"), null=True, blank=True,
                                validators=[validate_non_empty_text])
    content = models.TextField(pgettext_lazy("News content", "Content"),
                               validators=[validate_non_empty_text])

    publish_date = models.DateField(_("Publish date"),
                                    validators=[MaxValueValidator(datetime.date.today)])
    # postgre ArrayField?
    keywords = models.JSONField(_("Keywords"), null=True, blank=True,
                                validators=[validate_json_array, MinLengthValidator(1)])
    doi = models.URLField(max_length=255, null=True, blank=True)  # some articles DO have same original articles
    original_source = models.URLField(
        _("Original Source"), null=True, blank=True, max_length=511,
        help_text='Some articles is written from other sources news site e.g. universities'
    )

    journal = models.ForeignKey(Association, null=True, blank=True,
                                verbose_name=_("Journal"),
                                limit_choices_to={'type': Association.AssociationType.Journal},
                                on_delete=models.SET_NULL, related_name='published_articles')  # TODO: related_name

    institution = models.ForeignKey(Association, null=True, blank=True,
                                    verbose_name=_("Institution"),
                                    limit_choices_to={'type': Association.AssociationType.Institution},
                                    on_delete=models.SET_NULL, related_name='researched_articles')

    funder = models.ForeignKey(Association, null=True, blank=True,
                               verbose_name=_("Funder"),
                               limit_choices_to={'type': Association.AssociationType.Funder},
                               on_delete=models.SET_NULL, related_name='funded_articles')

    tags = models.ManyToManyField(Tag, through=ArticleTag, through_fields=('article', 'tag'), related_name='articles')

    @property
    def associations(self):
        d = {}
        if self.journal:
            d['Journal'] = self.journal
        if self.funder:
            d['Funder'] = self.funder
        if self.institution:
            d['Institution'] = self.institution
        return d

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ["-publish_date"]
        constraints = [
            models.CheckConstraint(check=models.Q(publish_date__lte=Now(output_field=models.DateField())),
                                   name="article_publish_date")
        ]
        indexes = [
            models.Index(fields=['-publish_date']),
        ]

    def __str__(self):
        title = str(self.title)
        return title if (len(title)) < 100 else title[:97] + "..."

    # class Meta:
    #     constraints = [
    #         # https://docs.djangoproject.com/en/3.2/ref/models/options/#constraints
    #         models.CheckConstraint(check=models.Q(age__gte=18), name='age_gte_18'),
    #     ]

    # we can define funder and others as Proxy or base Association as Meta/Abstract class.

    # @property
    # def funder(self):
    # def journal(self):
    # def institution(self):

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     validate_json_array(self.keywords.value_from_object(self))

articles/templates/articles/article_detail.html
{% extends 'base_nav_sidemenu.html' %}
{% load jalali_tags %}
{% load static %}
{% load i18n %}
{% load customtemplates %}
{% block title %}
  {% translate "Article" %}
{% endblock %}

{% block sidemenu %}
  <script>
      document_ready(() => {
          init_tomselect();
      })
  </script>

  <div class="mx-2">
    <div id="np-article-tags" class="d-flex flex-wrap gap-1 overflow-auto me-0" style="max-height: 190px;"
         hx-get="{% url 'articles:article-tags' article.id %}"
         hx-target="this"
         hx-swap="innerHTML"
         hx-ext='path-deps'
         hx-trigger="load, path-deps"
         path-deps="articles/{{ article.id }}/tags/*"> {# triggered manually from np_article_tags.js file #}
    </div>

    <div class="mt-2"></div>
    {% translate "Add a tag" as i18n_TagHing %}
    <label for="np-search-tag" hidden>{{ i18n_TagHing }}:</label>
    <input type="text" id="np-search-tag" class="form-control-sm text-wrap" placeholder="{{ i18n_TagHing }}..."/>
    <div id="np-tag-validation-error" class="invalid-feedback invisible"></div>
    <hr/>

    {# Comment #}
    <div hx-get="{% url 'articles:article-comments' article.id %}"
         hx-trigger="load"
         hx-target="this"
         hx-swap="outerHTML">
    </div>
  </div>
{% endblock sidemenu %}



{% block dynamic_content %}
  <div dir="ltr" class="row overflow-auto h-100">
    <input id="np_article_id" type="hidden" value="{{ article.id }}"/> {# np_article_tags.js needs article.id #}

    <div class="mt-3"></div>

    {# Article Main Info #}
    <h3 class="display-6">{{ article.title }}</h3>
    {% if article.subtitle %}
      <p class="text-muted fs-5">{{ article.subtitle }}</p>
    {% endif %}
    <div class="mt-4"></div>
    <div>{{ article.content|escape|linebreaks }}</div>

    <hr class="my-3"/>

    {# Article Extra Info #}
    {% get_current_language_bidi as LANGUAGE_BIDI %}
    <div {% if LANGUAGE_BIDI %}dir="rtl{% endif %}">
      <div class="row mb-2">
        <div class="col col-sm-3 form-label">{% translate "Publish date" %}:</div>
        <div class="col col-sm-9 align-self-center">
          {{ article.publish_date|to_jalali:'%d %B %Y'|l10n_nums }}
        </div>
      </div>

      <div class="row mb-2">
        {# TODO: add extra context to ArticleDetails tag, return original website name by getting Article.url #}
        <div class="col col-sm-3 form-label">{% translate "Crawled from" %}:</div>
        <div class="col col-sm-9 align-self-center">
          <a href="{{ article.url }}" target="_blank">{{ article.url|truncatechars:30 }} <i
              class="bi bi-box-arrow-up-right"></i></a>
        </div>
      </div>

      {% if article.keywords %}
        <div class="row mb-2">
          <div class="col col-sm-3 form-label">{% translate "Sites keywords" %}:</div>
          <div class="col col-sm-9 align-self-center">
            {% for keyword in article.keywords %}
              <span class="badge bg-secondary rounded-pill">{{ keyword }}</span>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      {% if article.doi %}
        <div class="row mb-2">
          <div class="col col-sm-3 form-label">{% translate 'Paper' %}:</div>
          <div class="col col-sm-9 align-self-center">
            <a href="https://libgen.is/scimag/?q={{ article.doi|url_path|slice:"1:"|url_encoded }}" target="_blank">
              {% translate 'See in Libgen' %} <i class="bi bi-box-arrow-up-right"></i>
            </a>
          </div>
        </div>
      {% endif %}

      {% if article.original_source %}
        <div class="row mb-2">
          <div class="col col-sm-3 col-form-label">{% translate "Originally published in" %}:</div>
          <div class="col col-sm-9 align-self-center">
            <a href="{{ article.original_source }}">
              {{ article.original_source|truncatechars:50 }}
            </a>
          </div>
        </div>
      {% endif %}

      {% for name, association in article.associations.items %}
        <div class="row mb-2">
          <div class="col col-sm-3 form-label">{% translate name %}:</div>
          <div class="col col-sm-9 align-self-center hstack gap-2"
               hx-select="#np-content"
               hx-target="#np-content"
               hx-swap="outerHTML"
               hx-push-url="true">
            <a class="link-dark"
               href="{% url 'articles:association-profile' pk=association.pk %}"
               hx-get="{% url 'articles:association-profile' pk=association.pk %}">
              {{ association.name }}
            </a>
            <a class="ms-auto text-nowrap"
               href="{% url 'articles:articles-by-association' association_id=association.pk %}"
               hx-get="{% url 'articles:articles-by-association' association_id=association.pk %}">
              <small>{% trans 'See related news' %}</small></a>
          </div>
        </div>
      {% endfor %}</div>

    <div class="mt-3"></div>
  </div>
{% endblock dynamic_content %}

{% comment %}<script>
      document_ready(() => {
          make_tab_active('');
          init_tomselect();
      })
  </script>{% endcomment %}

articles/templates/articles/article_list_textsearch.html
{% extends 'articles/tab_articles.html' %}
{% load crispy_forms_filters %}
{% load i18n %}
{% load customtemplates %}
{% load jalali_tags %}
{% load crispy_forms_tags %}

{% block sidemenu %}
  {% with active_menu='textsearch' %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block dynamic_content %}
  <div id="np-article-list">
    <div class="mt-3"></div>

    {# SEARCH INPUT #}
    <div class="row">
      <form method="get" enctype="application/x-www-form-urlencoded"
          {#            action="{% url 'articles:articles-text-search' %}"#}
            hx-get="{% url 'articles:articles-text-search' %}"
            hx-push-url="true"
            hx-swap="outerHTML"
            hx-target="#np-dynamic-content"
            hx-select="#np-dynamic-content">
        {#    {% crispy form %}#}
        <div class="row">
          <div class="mx-auto hstack gap-2 justify-content-center">
            <div class="col-md-8 flex-grow-1 flex-md-grow-0 mb-3">
              <div class="input-group">
                <label for="np-textsearch" hidden></label>
                <input id="np-textsearch" dir="ltr" type="text" name="q" maxlength="100" class="form-control"
                       value="{{ form.q.value|default_if_none:"" }}"/>
                <span class="input-group-text bg-primary bg-opacity-25 bi bi-search"
                      onclick="htmx.closest(this, 'form').requestSubmit()"></span>
              </div>
              <small class="form-text text-muted align-baseline">
                {{ form.q.help_text }}
              </small>
              {% trans form.q.field.widget.attrs.long_help_text as long_help_text %}
              <i class="bi bi-question-circle-fill text-primary"
                 data-bs-toggle="popover" data-bs-placement="bottom" data-bs-trigger="hover focus"
                 data-bs-html="true"
                 data-bs-content="{{ long_help_text|linebreaks }}">
              </i>
              {% if form.non_field_errors %}
                <div class="col-md-8 text-danger">
                  <span class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"></span>
                  {{ form.non_field_errors.as_text|cut:"*" }}
                </div>
              {% endif %}
            </div>
            <div class="align-self-start btn btn btn-primary"
                 onclick="htmx.closest(this, 'form').requestSubmit()">
              {% trans 'Search' %}
            </div>
          </div>
          {# Force next columns to break to new line #}
          <div class="w-100"></div>
          <div class="col-auto me-auto">
            <span class="fs-6">{% translate 'More Filters' %}</span>
            <i class="small bi bi-caret-down-fill" role="button" data-bs-toggle="collapse"
               data-bs-target="#np-advanced-search-extra"></i>
          </div>
          <div class="w-100 mb-3"></div>
          <div id="np-advanced-search-extra"
               class="collapse row {% if show_advanced_filters %}show{% endif %}">
            <div class="col-12 col-lg-6">{{ form.journal|as_crispy_field }}</div>
            <div class="col-12 col-lg-6">{{ form.institution|as_crispy_field }}</div>
            <div class="col-12 col-lg-6">{{ form.funder|as_crispy_field }}</div>
            <div class="w-100"></div>
            <div class="col-12 col-lg-6">{{ form.include_comments|as_crispy_field }}</div>
            <div class="w-100"></div>
            <div class="col-auto">
              <button hx-disable type="button" class="btn btn-outline-danger"
                      onclick="reset_form(this.closest('form'))">
                {% translate 'Reset' context "Form reset" %}
              </button>
            </div>
          </div>
        </div>
        {{ form.media }}

        {% comment %} There is bug in Django autocomplete light, that, when widget is loaded after DOM, widget
        initialization is not done completely. So here's the hack to manually add the missig class.
        see https://github.com/yourlabs/django-autocomplete-light/issues/819
        {% endcomment %}
        <script>
            $('[data-autocomplete-light-function]:not(.select2-hidden-accessible)').addClass('select2-hidden-accessible')
        </script>
      </form>
      {% if article_list %}
        <div class="col-auto mx-auto">{% include 'export.html' %}</div>
      {% endif %}
    </div>

    {% comment %}
    We use form.is_valid() as non-existing empty() method. If form is empty, page is loaded for the first time, hence,
    we want to avoid showing "No result find" in raw_article_list
    {% endcomment %}
    {% if form.is_valid %}
      {% include 'raw_article_list.html' %}
    {% endif %}
  </div>
{% endblock %}

articles/templates/articles/article_tags.html
{% if article.tags.all %}
  {% for tag in article.tags.all %}
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-tag pe-none">
        {{ tag.title }}
      </button>
      <button type="button" class="btn btn-tag"
              hx-confirm="Are you sure?"
              hx-swap="outerHTML"
              hx-target="closest .btn-group"
          {# remove single tag or reload all of tags? second is safer #}
              hx-delete="{% url 'articles:article-tag-addOrRemove' article.pk tag.pk %}">
        &times;
      </button>
    </div>
  {% endfor %}
{% endif %}

articles/templates/articles/base_article_list.html
{% extends 'articles/tab_articles.html' %}

{% block dynamic_content %}
  {% include 'sortable_article_list.html' %} {# use inclusion tag, pass csv, word_cloud and sord options #}
{% endblock %}

articles/templates/articles/comment_detail.html
{% load i18n %}
{# first time we fetch comment in article template, so we have 'article object #}
{# next times this is got directly by ajax so we have to get article_id from path params #}

<div class="card border-dark text-dark bg-light mb-2"
     hx-target="this" {# to child nodes to inherit #}
     hx-swap="outerHTML">
  <div class="card-header d-flex align-items-baseline justify-content-between">
    <span>{% translate "Your comment" %}</span>
    <span>
      {% if comment %}
        <button class="btn btn-sm btn-outline-danger bi bi-trash"
                hx-post="{% url 'articles:article-usercomment-delete' comment.article.id %}"
                hx-confirm="Are you sure?">
        </button>
      {% endif %}
      <button class="btn btn-sm btn-outline-secondary bi bi-pen"
          {% if comment %}
              hx-get="{% url 'articles:article-usercomment-update' comment.article.id %}"
          {% else %}
            {# see get_context_data in CommmentCreateView #}
              hx-get="{% url 'articles:article-comment-create' article.id %}"
          {% endif %}>
      </button>
    </span>
  </div>
  <div class="card-body" style="min-height: 15rem;">
    {% if comment.content %}
      {{ comment.content|linebreaks|urlizetrunc:30 }}
    {% else %} {# &hellip; #}
      <span
          class="text-muted fs-6 fst-italic">{% translate "...No comment" context "as comment form placeholder" %}</span>
    {% endif %}
  </div>
</div>

articles/templates/articles/tab_tags.html
{% extends 'articles/base_tag_page.html' %}

{% block dynamic_content %}
  {% include 'articles/tag_list.html' %}
{% endblock %}