articles/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from articles.views import (AddOrRemoveArticleTagView, ArticleTagSearchView, AllArticlesListView, ArticlesByTagListView,
                            ArticlesByAssociationListView, ArticleCommentsListView, CommentCreateView,
                            CommentDetailView, ArticleDetailView, ArticleTagsListView, create_tag_and_add_to_article,
                            AssociationAutocompleteView, SearchableAssociationsListView, CommentUpdateView,
                            CommentDeleteView, DigestListView, DigestDetailView, ReportsTabView, TagTrendReportView,
                            MostUsedTagsReportView, CSVReportView, TagAutocompleteView, AllTagsListView,
                            CreatedByMeTagsListView, TagCoOccurrenceReportView, VisualWordCloudReportView,
                            TextualWordCloudReportView, TagCreateView, ToggleTagFollowershipView,
                            FollowedByMeTagsListView, TextSearchArticleListView, FollowedArticlesListView,
                            CommentedArticlesListView, AssociationProfileView, AssociationProfileCreateView,
                            AssociationProfileUpdateView, MetaTagsListView, CommentedByMeArticlesListView)
from newsprocessor_dashboard import settings

app_name = 'articles'

# ******** ATTENTION! *********
# There are few cases we hard coded urls.
# 1. Wherever Using HTMX path-deps.
#       (currently tag lists and article tags, so careful with 'tags/*' and 'articles/<id>/tags/*'
# 2. Sending request to add tag to article. -> 'articles/<id>/tags/<id>'

urlpatterns = [
    # region Tags
    path('tags/', include([
        # Queries
        path('', AllTagsListView.as_view(), name='tags-all'),
        path('created/', CreatedByMeTagsListView.as_view(), name='tags-created-by-me'),
        path('followed/', FollowedByMeTagsListView.as_view(), name='tags-followed-by-me'),
        path('meta/', MetaTagsListView.as_view(), name='tags-meta'),
        path('search/autocomplete/', TagAutocompleteView.as_view(), name='tags-autocomplete'),

        # Single tag
        # path('<int:pk>/', TagDetailView.as_view(), name='tag-detail'),
        path('create/', TagCreateView.as_view(), name='tag-create'),
        # path('<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
        # path('<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),
        path('<int:pk>/followership/', ToggleTagFollowershipView.as_view(), name='tag-toggle-followership'),
    ])),
    # endregion

    # region Articles
    path('articles/', include([
        # Queries
        path('', AllArticlesListView.as_view(), name='articles-all'),
        path('interested/', FollowedArticlesListView.as_view(), name='articles-by-followed-tags'),
        path('commented/', CommentedArticlesListView.as_view(), name='articles-commented'),
        path('commented-by-me/', CommentedByMeArticlesListView.as_view(), name='articles-commented-by-me'),
        path('by-tag/<int:tag_id>/', ArticlesByTagListView.as_view(), name='articles-by-tag'),
        path('by-association/<int:association_id>/', ArticlesByAssociationListView.as_view(),
             name='articles-by-association'),
        path('search/', TextSearchArticleListView.as_view(), name='articles-text-search'),

        # Single article details
        path('<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),

        path('<int:article_id>/', include([
            # Article tags
            path('tags/', ArticleTagsListView.as_view(), name='article-tags'),
            path('tags/create-and-add/', create_tag_and_add_to_article, name='article-tag-create-and-add'),
            path('tags/<int:tag_id>/', AddOrRemoveArticleTagView.as_view(), name='article-tag-addOrRemove'),
            path('tags/search/', ArticleTagSearchView.as_view(), name='article-tag-search'),

            # Article comment
            path('comments/', ArticleCommentsListView.as_view(), name='article-comments'),
            path('user_comment/', CommentDetailView.as_view(), name='article-usercomment-details'),
            path('comment/create/', CommentCreateView.as_view(), name='article-comment-create'),
            path('user_comment/update/', CommentUpdateView.as_view(), name='article-usercomment-update'),
            path('user_comment/delete/', CommentDeleteView.as_view(), name='article-usercomment-delete'),
        ]))
    ])),
    # endregion

    path('reports/', include([
        path('', ReportsTabView.as_view(), name='tabs-reports'),
        path('tag-trend/', TagTrendReportView.as_view(), name='reports-tag-trend'),
        path('most-used-tags/', MostUsedTagsReportView.as_view(), name='reports-most-used-tags'),
        path('tag-co-occurrence/', TagCoOccurrenceReportView.as_view(), name='reports-tag-co-occurrence'),
        path('visual-wordcloud/', VisualWordCloudReportView.as_view(), name='reports-visual-wordcloud'),
        path('textual-wordcloud/', TextualWordCloudReportView.as_view(), name='reports-textual-wordcloud'),
        path('csv/', CSVReportView.as_view(), name='reports-csv'),
    ])),

    path('digests/', include([
        path('', DigestListView.as_view(), name='digests-list'),
        path('<int:pk>/', DigestDetailView.as_view(), name='digest-detail')
    ])),

    path('assocs/', include([
        path('<slug:association_type>/', SearchableAssociationsListView.as_view(), name='association-list'),
        path('<slug:association_type>/search/', AssociationAutocompleteView.as_view(), name='assoc-autocomplete'),
        path('<int:pk>/profile/', AssociationProfileView.as_view(), name='association-profile'),
        path('<int:pk>/profile/create/', AssociationProfileCreateView.as_view(),
             name='association-profile-create'),
        path('<int:pk>/profile/update/', AssociationProfileUpdateView.as_view(),
             name='association-profile-update'),
    ])),
]

# https://testdriven.io/blog/django-static-files/
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsprocessor_dashboard/urls.py
from django.contrib.auth import views as auth_views

from articles.forms import LoginForm, CustomPasswordChangeForm
from articles.views import HomeView, CustomPasswordChangeView

"""newsprocessor_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.urls import path, include, reverse_lazy

admin.site.site_title = _("News website")
admin.site.site_header = _("News website admin panel")

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include([
        path('login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            authentication_form=LoginForm,
        ), name="login"),
        path('logout/', auth_views.LogoutView.as_view(), name="logout"),
        path('password_change/', CustomPasswordChangeView.as_view(
            success_url=reverse_lazy("home"),
            form_class=CustomPasswordChangeForm,
        ), name="password_change"),
    ])),

    path('', include('articles.urls')),
]

articles/models.py
import datetime

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinLengthValidator
from django.db import models
# TODO: Digest, Filter
from django.db.models.functions import Lower, Now
from django.urls import reverse
from django.utils.translation import pgettext_lazy, gettext_lazy as _
from django_countries.fields import CountryField

from articles.apps import ArticlesConfig
from articles.validators import *


# TODO: test validations using self.assertFieldOutput
class Tag(models.Model):
    # CITextField to case-insensitive fields. Only Postgres
    title = models.CharField(_("Title"), max_length=50, unique=True,
                             validators=[non_empty_english_string, MinLengthValidator(2)])
    creator = models.ForeignKey(User, null=True, blank=True,
                                verbose_name=pgettext_lazy("Tag creator", "Creator"),
                                on_delete=models.SET_NULL,
                                related_name='created_tags')
    followers = models.ManyToManyField(User, blank=True,
                                       verbose_name=pgettext_lazy("Tag followers", "Followers"),
                                       related_name="following_tags", )
    is_meta = models.BooleanField(_("Is meta"), default=False,
                                  help_text=_("Meta tags are not applied to articles automatically"))

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
        ordering = ['title']
        constraints = [
            models.UniqueConstraint(
                Lower('title'),
                name='unique case insensitive title'
            ),
        ]

    def get_absolute_url(self):
        return reverse('articles:tag-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


# class AlternativeTitle(models.Model):
#     title = models.CharField(_("Title"), max_length=24, unique=True,
#                              validators=[non_empty_english_string, MinLengthValidator(2)])
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='alternative_names')
#
#     class Meta:
#         verbose_name = _("Alternative title")
#         verbose_name_plural = _("Alternative titles")
#         ordering = ['tag__title', 'title']
#         constraints = [
#             models.UniqueConstraint(
#                 Lower('title'),
#                 name='unique case insensitive title'
#             ),
#         ]


class ArticleTag(models.Model):
    # TODO: user. settings.AUTH_USER_MODEL --> django.contrib.auth.get_user_model()
    added_by = models.ForeignKey(User, null=True, blank=True,
                                 on_delete=models.SET_NULL,
                                 related_name='applied_tags')

    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)  # , related_name='used_cases')
    article = models.ForeignKey('Article', on_delete=models.CASCADE)  # , related_name='tags')

    # auto_applied = models.BooleanField(_("Auto applied"), default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['tag', 'article'], name='unique_tag_per_article'),
        ]

    # noinspection PyUnresolvedReferences
    def __str__(self):
        return f"{self.tag.title} on {self.article.title[:25]}"


class JournalManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Journal)


class InstitutionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Institution)


class FunderManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Association.AssociationType.Funder)


class Association(models.Model):
    class AssociationType(models.IntegerChoices):
        Journal = 0, _('Journal')
        Institution = 1, _('Institution')
        Funder = 2, _('Funder')

    name = models.CharField(_("Name"), max_length=255, validators=[validate_non_empty_text])
    type = models.IntegerField(_("Type"), choices=AssociationType.choices)
    objects = models.Manager()  # First Manager becomes _default_manager by Django
    journals = JournalManager()
    institutions = InstitutionManager()
    funders = FunderManager()

    def type_object(self):
        return Association.AssociationType(self.type)

    def articles(self) -> models.Manager:
        if self.type == Association.AssociationType.Journal:
            return self.published_articles
        if self.type == Association.AssociationType.Institution:
            return self.researched_articles
        return self.funded_articles

    def get_absolute_url(self):
        return reverse('articles:association-profile', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _("Association")
        verbose_name_plural = _("Associations")
        constraints = [
            models.UniqueConstraint(fields=['name', 'type'], name='unique_name_per_type'),
        ]
        ordering = ['name']

    def __str__(self):
        return self.name[:50]


class AssociationProfile(models.Model):
    association = models.OneToOneField(Association, on_delete=models.CASCADE, primary_key=True, related_name='profile')
    custom_name = models.CharField(_('Persian name'), max_length=255)
    icon = models.ImageField(_('Icon'), upload_to=f'{ArticlesConfig.name}/associations/', null=True, blank=True)
    description = models.TextField(_('Description'), null=True, blank=True)
    country = CountryField(_('Country'), null=True, blank=True, blank_label=_('-- Select country --'))

    # country = models.CharField(_('Country'), choices=, null=True, blank=True)

    def __str__(self):
        return self.custom_name[:50]

    def get_absolute_url(self):
        return self.association.get_absolute_url()

    class Meta:
        verbose_name = _("Association Profile")
        verbose_name_plural = _("Association Profiles")


# TODO: test validations using self.assertFieldOutput
class Article(models.Model):
    default_pagination = 8

    url = models.URLField(_("URL"), unique=True)
    title = models.CharField(_("Title"), max_length=255, unique=True,  # avoiding duplicate or very similar articles
                             validators=[validate_non_empty_text])
    subtitle = models.TextField(pgettext_lazy("News subtitle", "Subtitle"), null=True, blank=True,
                                validators=[validate_non_empty_text])
    content = models.TextField(pgettext_lazy("News content", "Content"),
                               validators=[validate_non_empty_text])

    publish_date = models.DateField(_("Publish date"),
                                    validators=[MaxValueValidator(datetime.date.today)])
    # postgre ArrayField?
    keywords = models.JSONField(_("Keywords"), null=True, blank=True,
                                validators=[validate_json_array, MinLengthValidator(1)])
    doi = models.URLField(max_length=255, null=True, blank=True)  # some articles DO have same original articles
    original_source = models.URLField(
        _("Original Source"), null=True, blank=True, max_length=511,
        help_text='Some articles is written from other sources news site e.g. universities'
    )

    journal = models.ForeignKey(Association, null=True, blank=True,
                                verbose_name=_("Journal"),
                                limit_choices_to={'type': Association.AssociationType.Journal},
                                on_delete=models.SET_NULL, related_name='published_articles')  # TODO: related_name

    institution = models.ForeignKey(Association, null=True, blank=True,
                                    verbose_name=_("Institution"),
                                    limit_choices_to={'type': Association.AssociationType.Institution},
                                    on_delete=models.SET_NULL, related_name='researched_articles')

    funder = models.ForeignKey(Association, null=True, blank=True,
                               verbose_name=_("Funder"),
                               limit_choices_to={'type': Association.AssociationType.Funder},
                               on_delete=models.SET_NULL, related_name='funded_articles')

    tags = models.ManyToManyField(Tag, through=ArticleTag, through_fields=('article', 'tag'), related_name='articles')

    @property
    def associations(self):
        d = {}
        if self.journal:
            d['Journal'] = self.journal
        if self.funder:
            d['Funder'] = self.funder
        if self.institution:
            d['Institution'] = self.institution
        return d

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ["-publish_date"]
        constraints = [
            models.CheckConstraint(check=models.Q(publish_date__lte=Now(output_field=models.DateField())),
                                   name="article_publish_date")
        ]
        indexes = [
            models.Index(fields=['-publish_date']),
        ]

    def __str__(self):
        title = str(self.title)
        return title if (len(title)) < 100 else title[:97] + "..."

    # class Meta:
    #     constraints = [
    #         # https://docs.djangoproject.com/en/3.2/ref/models/options/#constraints
    #         models.CheckConstraint(check=models.Q(age__gte=18), name='age_gte_18'),
    #     ]

    # we can define funder and others as Proxy or base Association as Meta/Abstract class.

    # @property
    # def funder(self):
    # def journal(self):
    # def institution(self):

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     validate_json_array(self.keywords.value_from_object(self))

articles/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}"
      {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
  <title>{% block title %}{% endblock %}</title>
  {#------------------ META ----------------------#}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="htmx-config" content='{"timout":3000, "refreshOnHistoryMiss":"true"}'>
  {#------------------ CSS ----------------------#}
  <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}"/>
  {% if LANGUAGE_BIDI %} {# RTL lang #}
    <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/bootstrap.rtl.min.css' %}">
  {% else %}
    <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/bootstrap.min.css' %}">
  {% endif %}
  <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/bootstrap-icons.css' %}">
  <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/news-processor.css' %}"/>
  <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/tom-select.bootstrap5.min.css' %}">
  {% if LANGUAGE_CODE == 'fa' %}
    <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/news-processor-rtl-extra.css' %}"/>
  {% endif %}
  {% if LANGUAGE_BIDI %} {# RTL lang #}
    <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/select2-bootstrap-5-theme.rtl.min.css' %}">
  {% else %}
    <link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/select2-bootstrap-5-theme.min.css' %}">
  {% endif %}
  {#------------------ JS ----------------------#}
  <script crossorigin="anonymous" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/htmx.min.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/path-deps.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/news_processor.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/np_list_sort.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/tom-select.complete.min.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/np_article_tags.js' %}"></script>
  <script crossorigin="anonymous" src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body>
{# Notification #}
<div id="np-notification-container" hx-swap-oob="true"
     class="container-fluid np-page-width mx-auto position-fixed top-100 start-50 translate-middle-x"
     style="z-index: 999">
  {% if messages %}
    {% for message in messages %}
      <div class="toast-container position-absolute bottom-0 end-0 p-3" style="z-index: 2000">
        <div class="toast {{ message.tags }} align-items-center text-white border-0 hide" {# shadow #}
             role="alert" aria-live="assertive" aria-atomic="true">
          <div class="d-flex">
            <div class="toast-body">
              {#        <img src="..." class="rounded me-2" alt="...">#}
              <div class="fs-6">{{ message }}</div>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto"
                    data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}
</div>

<div id="np-body"> {# htmx doesn't work with hx-select="body" hx-target="body" #}
  {% block body %}{% endblock %}
</div>
{# https://www.mattlayman.com/blog/2021/how-to-htmx-django/ #}
{# https://github.com/bigskysoftware/htmx/issues/70#issuecomment-951462597 #}
<script>
    // htmx.config.timeout = 1;{# ms #}
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    document.body.addEventListener('htmx:pushedIntoHistory', (evt) => {
        localStorage.removeItem('htmx-history-cache')
    })
</script>
</body>
</html>

articles/templates/base_nav.html
{% extends 'base.html' %}
{% load customtemplates %}
{% block title %}
  Home
{% endblock title %}

{% block body %}
  {% comment %} MENU TOP BAR {% endcomment %}
  {% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}
  {% comment %} class="np-max-width"{% endcomment %}

  <div id="np-content" class="container-fluid np-page-width m-auto"> {# hx-history-elt #}
    {% block content %}
    {% endblock %}
  </div>
{% endblock body %}

articles/templates/base_nav_no_menu.html
{% extends 'base_nav.html' %}
{% block content %}
  <div class="row row-cols-1 h-100">
    <section id="np-dynamic-content" class="col np-bg-gray h-100 overflow-auto">
      {% block dynamic_content %}
      {% endblock %}
    </section>
  </div>
{% endblock content %}

articles/templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand px-0 navbar-dark np-bg-dark-900 sticky-top np-sticky-bar">
  <div class="container-md np-page-width">
    <span class="list-group navbar-brand me-5">
      <span class="h4 mb-0">{{ user.get_full_name|default:user.username }}</span>
      {% if user.is_superuser %}
        <span class="h6 w-100 text-center">admin</span>
      {% endif %}
    </span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarNav" class="collapse navbar-collapse">
      {# TABS (Articles, Tags, Digests) #}
      <div id="np-tabs" class="navbar-nav gap-3 me-auto" role="tablist"
          {% comment %}We want to seem single-page but at the same time route with urls.
           So we fetch full pages, but swap only changed parts {% endcomment %}
           hx-boost="true"
           hx-select="#np-body"
           hx-target="#np-body"
           hx-swap="outerHTML"
           hx-push-url="true">
        {# if we don't want history and only change in browser url, we should use HX-Push resposne header #}
        <a id="np-articles-tab" class="nav-link {% if active_tab == 'articles' %}active{% endif %}"
            {#           data-bs-toggle="pill" data-bs-target="#np-articles" type="button" role="tab"#}
           href="{% url 'articles:articles-all' %}">
          {% translate "Articles" context "tab title" %}
        </a>
        <a id="np-tags-tab" class="nav-link {% if active_tab == 'tags' %}active{% endif %}"
            {#           data-bs-toggle="pill" data-bs-target="#np-tags" type="button" role="tab"#}
           href="{% url 'articles:tags-all' %}">
          {% translate "Tags" %}
        </a>
        <a id="np-associations-tab" class="nav-link {% if active_tab == 'associations' %}active{% endif %}"
            {#           data-bs-toggle="pill" data-bs-target="#np-tags" type="button" role="tab"#}
           href="{% url 'articles:association-list' association_type='Journal' %}">
          {% translate "Associations" %}
        </a>
        {% comment %}<a id="np-inbox-tab" class="nav-link {% if active_tab == 'inbox' %}active{% endif %}"
           href="{% url 'articles:digests-list' %}">
          {% translate "Inbox" %}
        </a>{% endcomment %}
        <a id="np-reports-tab" class="nav-link {% if active_tab == 'reports' %}active{% endif %}"
           href="{% url 'articles:tabs-reports' %}"
           hx-boost="unset">
          {% translate "Reports" %}
        </a>
      </div>

      {% comment %} MORE OPTIONS (Logout, Change Pass) {% endcomment %}
      <div class="nav-item navbar-nav dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="np-navbar-more-dropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
          {% translate "More" context "in nav menu" %}
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="np-navbar-more-dropdown">
          <li><a class="dropdown-item" href="#">{% translate "About the site" %}</a></li>
          <li><a class="dropdown-item" href="{% url 'password_change' %}">{% translate "Change Password" %}</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{% url 'logout' %}">{% translate "Logout" %}</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

articles/templates/raw_article_list.html
{% load i18n %}
{% load customtemplates %}
{% load jalali_tags %}

{% if article_list %}
  <hr/>
  <div class="text-muted fs-6 mb-2">
    {% if page_obj.paginator.count != 0 %}
      {{ page_obj.paginator.count|l10n_nums }} {% translate 'articles found' context "like 5 articles found" %}
    {% endif %}
  </div>
{% else %}
  <div class="text-center fw-bold text-muted fs-5 mt-4">
    {% translate 'No articles found' %}
  </div>
{% endif %}

<div class="list-group list-group-flush rounded-3">
  {% for article in article_list %}
    <div class="list-group-item list-group-item-action" dir="ltr"> {% comment %}dir="ltr"{% endcomment %}
      <div class="w-100">
        {% get_current_language as LANGUAGE_CODE %}
        <div class="float-start
{% if LANGUAGE_CODE == 'fa' %}me-5 text-start
{% else %}float-end ms-5 text-end
{% endif %}">
          {% if LANGUAGE_CODE == 'fa' %}
            <small class="text-nowrap" dir="rtl">
              {{ article.publish_date|to_jalali:'%d %B %Y'|l10n_nums }}
            </small>
          {% else %}
            <small class="text-nowrap">
              {{ article.publish_date }} {# date:"SHORT_DATE_FORMAT" #}
            </small>
          {% endif %}
          <div class="clearfix"></div>
        </div>
        <a class="link-dark" href="{% url "articles:article-detail" article.id %}"
           hx-get="{% url "articles:article-detail" article.id %}"
           hx-select="#np-content"
           hx-target="#np-content"
           hx-swap="outerHTML"
           hx-push-url="true"><h5>{{ article.title|truncatechars:100 }}</h5>
        </a>
      </div>
      <div>{{ article.content|default:""|truncatechars:130 }}</div>
      {% with article_tags=article.tags.all %}
        {% if article_tags %}
          <div class="mb-1"></div>
          {% for tag in article_tags|slice:':5' %}
            <span class="badge bg-tag rounded-pill">{{ tag }}</span>
          {% endfor %}
          {% if article_tags|length > 5 %}
            <span class="badge bg-primary rounded-pill">+{{ article_tags|length|add:'-5' }}</span>
          {% endif %}
          {% if article.has_comments %}
            <span class="align-baseline {% if LANGUAGE_CODE == 'fa' %}float-start me-4{% else %}float-end ms-4{% endif %}">
              <i class="text-black text-opacity-75 bi bi-stickies-fill"></i>
            </span>
          {% endif %}
        {% endif %}
      {% endwith %}
    </div>
  {% endfor %}
</div>

<div class="mt-3"></div>
{% include 'pagination.html' %}

articles/templates/sortable_article_list.html
{#{% load humanize %}#}
{% load i18n %}
{% load l10n %}
{% load customtemplates %}
{% load jalali_tags %}
<div id="np-article-list">
  <div class="mt-3"></div>

  {# SORT TYPE #}
  {% if article_list %}
    <div class="row row-cols-auto gx-4 gy-2 justify-content-between align-items-baseline">

      {% if sortable %}
        <div class="d-inline-flex align-items-baseline">
          {% include 'sort.html' %}
        </div>
      {% endif %}

      {% include 'export.html' %}
    </div>
  {% endif %}
  <div class="mt-2"></div>
  {% include 'raw_article_list.html' %}
</div>